# Generated by Django 6.0.1 on 2026-01-20 18:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('persona_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=80)),
                ('apellidos', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=120, null=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Teléfono inválido.', regex='^[0-9+\\s()-]{6,20}$')])),
            ],
            options={
                'db_table': 'persona',
                'indexes': [models.Index(fields=['apellidos', 'nombres'], name='persona_apellid_d63688_idx')],
            },
        ),
    ]
