# Generated by Django 6.0.1 on 2026-01-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('holding_id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_empresa', models.IntegerField(unique=True)),
                ('razon_social', models.CharField(max_length=150)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('empresa_estado', models.IntegerField()),
            ],
        ),
    ]
