# Generated by Django 6.0.1 on 2026-01-20 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holding_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holding',
            options={'managed': False},
        ),
    ]
