# Generated by Django 6.0.1 on 2026-01-21 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holding_app', '0002_alter_holding_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='holding',
            table='holding_app_holding',
        ),
    ]
