# Generated by Django 6.0.1 on 2026-01-27 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('proveedor_id', models.AutoField(primary_key=True, serialize=False)),
                ('razon_social', models.CharField(max_length=150)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('empresa_estado', models.BooleanField()),
            ],
            options={
                'db_table': 'proveedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('producto_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=180)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo_fijo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='ProveedorProducto',
            fields=[
                ('proveedor_producto_id', models.AutoField(primary_key=True, serialize=False)),
                ('uom_compra', models.CharField(blank=True, max_length=20, null=True)),
                ('producto', models.ForeignKey(db_column='producto_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='proveedor_productos', to='compras_app.producto')),
                ('proveedor', models.ForeignKey(db_column='proveedor_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='proveedor_productos', to='compras_app.proveedor')),
            ],
            options={
                'db_table': 'proveedor_producto',
            },
        ),
        migrations.CreateModel(
            name='ProveedorProductoPrecio',
            fields=[
                ('proveedor_producto_precio_id', models.AutoField(primary_key=True, serialize=False)),
                ('precio_neto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('moneda', models.CharField(default='CLP', max_length=10)),
                ('proveedor_producto', models.ForeignKey(db_column='proveedor_producto_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='precios', to='compras_app.proveedorproducto')),
            ],
            options={
                'db_table': 'proveedor_producto_precio',
            },
        ),
        migrations.DeleteModel(
            name='Holding',
        ),
        migrations.AddConstraint(
            model_name='proveedorproducto',
            constraint=models.UniqueConstraint(fields=('proveedor', 'producto'), name='uq_proveedor_producto'),
        ),
    ]
