# Generated by Django 6.0.1 on 2026-01-31 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras_app', '0002_proveedor_producto_proveedorproducto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('compra_id', models.AutoField(primary_key=True, serialize=False)),
                ('folio', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_emision', models.DateField()),
                ('fecha_requerida', models.DateField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('total_neto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_iva', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'compra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoDocumento',
            fields=[
                ('estado_documento_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'estado_documento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('moneda_id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'moneda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('tipo_documento_id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'tipo_documento',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='proveedorproducto',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='proveedorproductoprecio',
            options={'managed': False},
        ),
        migrations.CreateModel(
            name='HistorialCompra',
            fields=[
                ('historial_compra_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_evento', models.DateTimeField(auto_now_add=True)),
                ('folio', models.CharField(blank=True, max_length=30, null=True)),
                ('compra', models.ForeignKey(db_column='compra_id', on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='compras_app.compra')),
                ('estado_documento', models.ForeignKey(db_column='estado_documento_id', on_delete=django.db.models.deletion.PROTECT, to='compras_app.estadodocumento')),
                ('tipo_documento', models.ForeignKey(db_column='tipo_documento_id', on_delete=django.db.models.deletion.PROTECT, to='compras_app.tipodocumento')),
            ],
            options={
                'db_table': 'historial_compra',
                'ordering': ['-fecha_evento'],
            },
        ),
    ]
