# Generated by Django 6.0.2 on 2026-02-19 19:05

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras_app', '0003_compra_estadodocumento_moneda_tipodocumento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompraItem',
            fields=[
                ('compra_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('nro_linea', models.IntegerField(default=1)),
                ('descripcion_libre', models.CharField(blank=True, max_length=255, null=True)),
                ('cantidad', models.DecimalField(decimal_places=3, default=1, max_digits=14)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('afecta_iva', models.BooleanField(default=True)),
                ('iva_porcentaje', models.DecimalField(decimal_places=2, default=19.0, max_digits=5)),
                ('subtotal_neto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('subtotal_iva', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('subtotal_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
            options={
                'db_table': 'compra_item',
                'ordering': ['nro_linea'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FacturaIntercompany',
            fields=[
                ('factura_ic_id', models.AutoField(primary_key=True, serialize=False)),
                ('folio', models.CharField(max_length=30)),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now)),
                ('recargo_porcentaje', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5)),
                ('total_neto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_iva', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'factura_intercompany',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FacturaIntercompanyItem',
            fields=[
                ('factura_ic_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=3, default=1, max_digits=14)),
                ('precio_base', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('afecta_iva', models.BooleanField(default=True)),
                ('iva_porcentaje', models.DecimalField(decimal_places=2, default=Decimal('19.00'), max_digits=5)),
                ('subtotal_neto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('subtotal_iva', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('subtotal_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
            options={
                'db_table': 'factura_intercompany_item',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='historialcompra',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='documentos_compra/'),
        ),
        migrations.AddField(
            model_name='historialcompra',
            name='fecha_documento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historialcompra',
            name='fecha_evento',
            field=models.DateTimeField(),
        ),
    ]
